plugins {
    id 'com.android.application'
}

android {
    namespace 'com.whitesr09.charecterbuild'
    compileSdk 35

    defaultConfig {
        applicationId 'com.whitesr09.charecterbuild'
        minSdk 26
        targetSdk 34
        versionCode 9
        versionName '1.6.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
